version: 2

project_name: openfga-authzen

before:
  hooks:
    - make generate-mocks

builds:
  -
    main: ./cmd/openfga
    binary: openfga
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w"
      - "-X github.com/aaguiarz/openfga/internal/build.Version=v{{ .Version }}"
      - "-X github.com/aaguiarz/openfga/internal/build.Commit={{.Commit}}"
      - "-X github.com/aaguiarz/openfga/internal/build.Date={{.Date}}"
      - "-X github.com/aaguiarz/openfga/internal/build.ProjectName={{.ProjectName}}"

dockers:
  - goos: linux
    goarch: amd64

    dockerfile: Dockerfile.goreleaser

    image_templates:
      - "openfga/openfga:latest-amd64"
      - "openfga/openfga:{{ .Tag }}-amd64"
      - "openfga/openfga:v{{ .Version }}-amd64"
      - "openfga/openfga:v{{ .Major }}-amd64"
      - "openfga/openfga:v{{ .Major }}.{{ .Minor }}-amd64"
      - "openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      # ghcr.io
      - "ghcr.io/openfga/openfga:latest-amd64"
      - "ghcr.io/openfga/openfga:{{ .Tag }}-amd64"
      - "ghcr.io/openfga/openfga:v{{ .Version }}-amd64"
      - "ghcr.io/openfga/openfga:v{{ .Major }}-amd64"
      - "ghcr.io/openfga/openfga:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"

    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"

    extra_files:
      - assets

  - goos: linux
    goarch: arm64

    dockerfile: Dockerfile.goreleaser

    image_templates:
      - "openfga/openfga:latest-arm64"
      - "openfga/openfga:{{ .Tag }}-arm64"
      - "openfga/openfga:v{{ .Version }}-arm64"
      - "openfga/openfga:v{{ .Major }}-arm64"
      - "openfga/openfga:v{{ .Major }}.{{ .Minor }}-arm64"
      - "openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
      # ghcr.io
      - "ghcr.io/openfga/openfga:latest-arm64"
      - "ghcr.io/openfga/openfga:{{ .Tag }}-arm64"
      - "ghcr.io/openfga/openfga:v{{ .Version }}-arm64"
      - "ghcr.io/openfga/openfga:v{{ .Major }}-arm64"
      - "ghcr.io/openfga/openfga:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"

    use: buildx

    build_flag_templates:
      - "--platform=linux/arm64"

    extra_files:
      - assets

docker_manifests:
  - name_template: ghcr.io/openfga/openfga:latest
    image_templates:
      - "ghcr.io/aaguiarz/openfga:latest-amd64"
      - "ghcr.io/aaguiarz/openfga:latest-arm64"
  - name_template: ghcr.io/openfga/openfga:v{{ .Version }}
    image_templates:
      - "ghcr.io/aaguiarz/openfga:v{{ .Version }}-amd64"
      - "ghcr.io/aaguiarz/openfga:v{{ .Version }}-arm64"
  - name_template: ghcr.io/openfga/openfga:v{{ .Major }}
    image_templates:
      - "ghcr.io/aaguiarz/openfga:v{{ .Major }}-amd64"
      - "ghcr.io/aaguiarz/openfga:v{{ .Major }}-arm64"
  - name_template: ghcr.io/openfga/openfga:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - "ghcr.io/aaguiarz/openfga:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/aaguiarz/openfga:v{{ .Major }}.{{ .Minor }}-arm64"
  - name_template: ghcr.io/openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - "ghcr.io/aaguiarz/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/aaguiarz/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"

release:
  github:
    owner: aaguiarz
    name: openfga

archives:
  - files:
      - assets

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
